### ISSUE TITLE
Can't build a widget dynamically in itemBuilder 

### ISSUE THREAD

**Issue by kateile** [EdsonBueno/infinite_scroll_pagination#26]
Thanks for amazing plugin it works just fine as intended however I was trying to create a wrapper of it to reduce boilerplate code and faced TypeError when returning a custom widget in **itemBuilder** using callback.

Below code can help reproduce this error
```dart
import 'package:flutter/material.dart';
import 'package:infinite_scroll_pagination/infinite_scroll_pagination.dart';

typedef PagedListFetcher<T> = Future<List<T>> Function(int offset);

typedef PagedListWidgetBuilder<T> = Widget Function(
    BuildContext context, T item);

Future<List<String>> fetchData(int offset) async {
  await Future.delayed(Duration(seconds: 2));
  return List<String>.generate(10, (index) => '${index + offset}th item');
}

class PostsPage extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Posts'),
      ),
      body: PagedList<String>(
        fetcher: (offset) {
          return fetchData(offset);
        },
        widgetBuilder: (context, item) {
          return Text(
            '$item',
          );
        },
      ),
    );
  }
}

/// Page list wrapper for Posts and Comments data.
class PagedList<T> extends StatefulWidget {
  /// This will build comment/post widget.
  final PagedListWidgetBuilder<T> widgetBuilder;

  /// This will fetch comment/post data at a time.
  final PagedListFetcher fetcher; //executor

  const PagedList({
    Key key,
    @required this.widgetBuilder,
    @required this.fetcher,
  }) : super(key: key);

  @override
  _PagedListState createState() => _PagedListState<T>();
}

class _PagedListState<T> extends State<PagedList> {
  static const _pageSize = 10;

  final PagingController<int, T> _pagingController =
      PagingController(firstPageKey: 0);

  @override
  void initState() {
    _pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return PagedListView<int, T>(
      pagingController: _pagingController,
      builderDelegate: PagedChildBuilderDelegate<T>(
        itemBuilder: (context, item, index) {
          //return Text(index.toString()); //THIS WORKS FINE
          return widget.widgetBuilder(context, item); //THIS THROWS ERROR
        },
      ),
    );
  }

  Future<void> _fetchPage(int pageKey) async {
    print('pageKey: $pageKey');
    final List<T> newData = await widget.fetcher(pageKey);
    print('newData: $newData');
    final isLastPage = newData.length < _pageSize;

    if (isLastPage) {
      _pagingController.appendLastPage(newData);
    } else {
      final nextPageKey = pageKey + newData.length;
      print('nextPageKey: $nextPageKey');
      _pagingController.appendPage(newData, nextPageKey);
    }
  }

  @override
  void dispose() {
    _pagingController.dispose();
    super.dispose();
  }
}
```
**Logs**
```
Performing hot restart...
Syncing files to device Android SDK built for x86...
Restarted application in 4,283ms.
I/flutter ( 7403): pageKey: 0
I/flutter ( 7403): newData: [0th item, 1th item, 2th item, 3th item, 4th item, 5th item, 6th item, 7th item, 8th item, 9th item]
I/flutter ( 7403): nextPageKey: 10

════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following _TypeError was thrown building:
type '(BuildContext, String) => Text' is not a subtype of type '(BuildContext, dynamic) => Widget'

When the exception was thrown, this was the stack: 
#0      _PagedListState.build.<anonymous closure> (package:test/pages/post/posts_page.dart:74:25)
#1      _PagedSliverBuilderState._buildListItemWidget (package:infinite_scroll_pagination/src/ui/paged_sliver_builder.dart:234:52)
#2      new AppendedSliverChildBuilderDelegate.<anonymous closure> (package:infinite_scroll_pagination/src/utils/appended_sliver_child_builder_delegate.dart:28:33)
#3      SliverChildBuilderDelegate.build (package:flutter/src/widgets/sliver.dart:449:22)
#4      SliverMultiBoxAdaptorElement._build (package:flutter/src/widgets/sliver.dart:1130:28)
...
════════════════════════════════════════════════════════════════════════════════════════════════════
```

Any help/fix/comment will be appreciated.

**Comment by EdsonBueno** [comment]
Hi @kateile .
Thank you for your feedback!

Simply replace this line:
```dart
class _PagedListState<T> extends State<PagedList> 
```

With this line:
```dart
class _PagedListState<T> extends State<PagedList<T>> 
```

**Comment by kateile** [comment]
@EdsonBueno  Thanks.
