### ISSUE TITLE
setState being called during Build

### ISSUE THREAD

**Issue by casvanluijtelaar** [EdsonBueno/infinite_scroll_pagination#38]
Hey I'm setting up a `PagedListview `that only has one item per page. I have several paged listviews that work fine but there's something odd about this one, i'm getting the following error on the `NotifiyNewpage `method:
<details>
  <summary>Error</summary>
  

  ```dart
I/flutter ( 5572): ══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
I/flutter ( 5572): The following assertion was thrown while dispatching notifications for
I/flutter ( 5572): CalendarGridPaginationService:
I/flutter ( 5572): setState() or markNeedsBuild() called during build.
I/flutter ( 5572): This AnimatedBuilder widget cannot be marked as needing to build because the framework is already in
I/flutter ( 5572): the process of building widgets.  A widget can be marked as needing to be built during the build
I/flutter ( 5572): phase only if one of its ancestors is currently building. This exception is allowed because the
I/flutter ( 5572): framework builds parent widgets before children, which means a dirty descendant will always be
I/flutter ( 5572): built. Otherwise, the framework might not visit this widget during this build phase.
I/flutter ( 5572): The widget on which setState() or markNeedsBuild() was called was:
I/flutter ( 5572):   AnimatedBuilder
I/flutter ( 5572): The widget which was currently being built when the offending call was made was:
I/flutter ( 5572):   SliverList
I/flutter ( 5572):
I/flutter ( 5572): When the exception was thrown, this was the stack:
I/flutter ( 5572): #0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
I/flutter ( 5572): #1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
I/flutter ( 5572): #2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
I/flutter ( 5572): #3      _AnimatedState._handleChange (package:flutter/src/widgets/transitions.dart:175:5)
I/flutter ( 5572): #4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
I/flutter ( 5572): #5      PagedDataSource.notifyNewPage (package:infinite_scroll_pagination/src/workers/paged_data_source.dart:129:5)
I/flutter ( 5572): #6      CalendarGridPaginationService.fetchItems (package:rvised/services/pagination/calendar_grid_pagination_service.dart:15:5)
  ```
</details>

I have tried replacing the `PagedChildBuilderDelegate` to just return a `Container`, same issue. when I replace the `PagedListView ` with a normal `ListView` it works just fine.

I can of course prevent the crash by adding a `isListingInProgress` check but that (naturally) breaks the pagination:

  ```dart
  @override
  void fetchItems(int pageKey) async {

    //if (isListingInProgress) return;

    final newItems = [ DateUtils.getMonth(pageKey)];

    final hasFinished = newItems.length < _pageSize;
    final nextPageKey = hasFinished ? null : pageKey + newItems.length;
    notifyNewPage(newItems, nextPageKey);
  }
  ```

One page containing 1 item is loaded, this item usually doesn't fill the list completely. 
I have been staring at this for several days and it's obviously going to be something extremely stupid I missed. But I hope you can help out ;)

<details>
  <summary>PagedListView implementation</summary>
  

  ```dart
@override
  Widget build(BuildContext context) {
    return Column(
      children: <Widget>[
        Expanded(
          child: PagedListView<int, CalendarMonth>(
            invisibleItemsThreshold: 1,
            cacheExtent: (MediaQuery.of(context).size.width / DateTime.daysPerWeek) * 6,
            padding: listPadding ?? EdgeInsets.zero,
            dataSource: dataSource,
            builderDelegate: PagedChildBuilderDelegate(
              itemBuilder: (context, item, index) => _MonthView(
                month: item.month,
                items: item.items,
                monthBuilder: monthBuilder,
                dayBuilder: dayBuilder,
                filter: dayFilter,
              ),
            ),
          ),
        ),
      ],
    );
  }
  ```
</details>

**Comment by EdsonBueno** [comment]
Hi @casvanluijtelaar.
I see that you're using an old version of the package. Can you update to the latest one? Maybe it'll fix your problem.
You'll have some work to migrate all your data sources to `PagingController`s. Use the [example project](https://github.com/EdsonBueno/infinite_scroll_pagination/tree/master/example) as a guide.
Another question: Why is your `PagedListView` inside a `Column` with only 1 child?
I'm closing the issue for now.
If you continue to have the same problem after the migration, ping me on [our chat](https://gitter.im/infinite_scroll_pagination/community) and I'll help you!
Thank you so much!

**Comment by EdsonBueno** [comment]
Good news @casvanluijtelaar!
I think your problem is the same as one that came up in another issue. If that's true, today's release (2.2.4) will fix it for you too!

**Comment by casvanluijtelaar** [comment]
That's awesome, I'll try and create a minimum reproducible version. Holding off on updating right away because it's a very large codebase. 

Thanks for looking into it!

**Comment by casvanluijtelaar** [comment]
Can confirm that 2.2.4 fixes this issue
