### ISSUE TITLE
RenderViewport issue

### ISSUE THREAD

**Issue by Purus** [EdsonBueno/infinite_scroll_pagination#43]
I am trying to implement this package and currently stuck with the below exception. I would need your help on this to successfully release my app.

````
I/flutter (28888): The following assertion was thrown building NotificationListener<ScrollNotification>:
I/flutter (28888): A RenderViewport expected a child of type RenderSliver but received a child of type
I/flutter (28888): RenderRepaintBoundary.
````

The complete error log is given below at the end below.

This is the main screen which is based on `CustomScrollView`.

```dart

class CategoryView extends StatelessWidget {
  final ChannelModel category;

  CategoryView(this.category);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: CustomScrollView(
        slivers: [
          SliverAppBar(
            title: Text(
              category.name,
              style: TextStyle(fontSize: 18.0),
            ),
          ),
          PostsList(category: category.slug),
        ],
      ),
    );
  }
}
```

Below is the list which will be used in the above main screen.

```dart

class PostsList extends StatefulWidget {
  final bool showOnlyFav;
  final bool showPopular;
  final String userId;
  final String label;
  final String category;
  final String favUserId;

  PostsList({
    this.showOnlyFav = false,
    this.showPopular = false,
    this.userId,
    this.category,
    this.label,
    this.favUserId,
  });

  @override
  _PostsListState createState() => _PostsListState();
}

class _PostsListState extends State<PostsList> {
  static const _pageSize = 20;
  final PagingController<int, PostModel> _pagingController =
      PagingController(firstPageKey: 0);

  @override
  void initState() {
    _pagingController.addPageRequestListener((pageKey) {
      _fetchPage(pageKey);
    });
    super.initState();
  }

  @override
  void dispose() {
    _pagingController.dispose();
    super.dispose();
  }

  Future<void> _fetchPage(int pageKey) async {
    try {
      final newItems = await FirestoreDatabase().postsStream(
          favUserId: widget.favUserId,
          category: widget.category,
          userId: widget.userId,
          label: widget.label,
          showPopular: widget.showPopular,
          showOnlyFav: widget.showOnlyFav);
      final isLastPage = newItems.length < _pageSize;
      if (isLastPage) {
        _pagingController.appendLastPage(newItems);
      } else {
        final nextPageKey = pageKey + newItems.length;
        _pagingController.appendPage(newItems, nextPageKey);
      }
    } catch (error) {
      _pagingController.error = error;
    }
  }

  @override
  Widget build(BuildContext context) {
    return PagedListView<int, PostModel>(
      pagingController: _pagingController,
      builderDelegate: PagedChildBuilderDelegate<PostModel>(
        itemBuilder: (context, item, index) => SingleDesignWidget(item),
      ),
    );
  }
}
```

The full exception is below.

```
I/flutter (28888): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28888): The following assertion was thrown building NotificationListener<ScrollNotification>:
I/flutter (28888): A RenderViewport expected a child of type RenderSliver but received a child of type
I/flutter (28888): RenderRepaintBoundary.
I/flutter (28888): RenderObjects expect specific types of children because they coordinate with their children during
I/flutter (28888): layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
I/flutter (28888): RenderSliver does not understand the RenderBox layout protocol.
I/flutter (28888): 
I/flutter (28888): The RenderViewport that expected a RenderSliver child was created by:
I/flutter (28888):   Viewport ← IgnorePointer-[GlobalKey#7c030] ← Semantics ← _PointerListener ← Listener ←
I/flutter (28888):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e85f2] ←
I/flutter (28888):   _PointerListener ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#c1f39] ←
I/flutter (28888):   RepaintBoundary ← ⋯
I/flutter (28888): 
I/flutter (28888): The RenderRepaintBoundary that did not match the expected child type was created by:
I/flutter (28888):   RepaintBoundary ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ←
I/flutter (28888):   Scrollable ← PagedListView<int, PostModel> ← PostsList ← Viewport ←
I/flutter (28888):   IgnorePointer-[GlobalKey#7c030] ← Semantics ← _PointerListener ← Listener ← _GestureSemantics ← ⋯
I/flutter (28888): 
I/flutter (28888): The relevant error-causing widget was:
I/flutter (28888):   PagedListView<int, PostModel> file:///D:/Flutter/womenly/lib/screens/posts/posts_list.dart:74:12
I/flutter (28888): 
I/flutter (28888): When the exception was thrown, this was the stack:
I/flutter (28888): #0      ContainerRenderObjectMixin.debugValidateChild.<anonymous closure> (package:flutter/src/rendering/object.dart:3123:9)
I/flutter (28888): #1      ContainerRenderObjectMixin.debugValidateChild (package:flutter/src/rendering/object.dart:3150:6)
I/flutter (28888): #2      MultiChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6191:25)
I/flutter (28888): #3      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5805:35)
I/flutter (28888): #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5501:5)
I/flutter (28888): #5      SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6117:11)
I/flutter (28888): ...     Normal element mounting (37 frames)
I/flutter (28888): #42     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #43     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): #44     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:225:11)
I/flutter (28888): ...     Normal element mounting (127 frames)
I/flutter (28888): #171    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #172    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (103 frames)
I/flutter (28888): #275    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #276    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (208 frames)
I/flutter (28888): #484    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #485    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (70 frames)
I/flutter (28888): #555    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #556    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (210 frames)
I/flutter (28888): #766    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #767    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (156 frames)
I/flutter (28888): #923    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #924    Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
I/flutter (28888): #925    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (28888): #926    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (28888): #927    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (28888): #928    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (28888): #929    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (28888): #930    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (28888): #931    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (28888): #932    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (28888): #933    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (28888): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (28888): 
I/flutter (28888): ════════════════════════════════════════════════════════════════════════════════════════════════════
I/flutter (28888): ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
I/flutter (28888): The following assertion was thrown building GlowingOverscrollIndicator(axisDirection: down, show:
I/flutter (28888): both sides, Color(0xff2196f3), dependencies: [_EffectiveTickerMode], state:
I/flutter (28888): _GlowingOverscrollIndicatorState#88371(tickers: tracking 4 tickers)):
I/flutter (28888): A RenderViewport expected a child of type RenderSliver but received a child of type RenderErrorBox.
I/flutter (28888): RenderObjects expect specific types of children because they coordinate with their children during
I/flutter (28888): layout and paint. For example, a RenderSliver cannot be the child of a RenderBox because a
I/flutter (28888): RenderSliver does not understand the RenderBox layout protocol.
I/flutter (28888): 
I/flutter (28888): The RenderViewport that expected a RenderSliver child was created by:
I/flutter (28888):   Viewport ← IgnorePointer-[GlobalKey#7c030] ← Semantics ← _PointerListener ← Listener ←
I/flutter (28888):   _GestureSemantics ← RawGestureDetector-[LabeledGlobalKey<RawGestureDetectorState>#e85f2] ←
I/flutter (28888):   _PointerListener ← Listener ← _ScrollableScope ← _ScrollSemantics-[GlobalKey#c1f39] ←
I/flutter (28888):   RepaintBoundary ← ⋯
I/flutter (28888): 
I/flutter (28888): The RenderErrorBox that did not match the expected child type was created by:
I/flutter (28888):   ErrorWidget-[#77063] ← NotificationListener<ScrollNotification> ← GlowingOverscrollIndicator ←
I/flutter (28888):   Scrollable ← PagedListView<int, PostModel> ← PostsList ← Viewport ←
I/flutter (28888):   IgnorePointer-[GlobalKey#7c030] ← Semantics ← _PointerListener ← Listener ← _GestureSemantics ← ⋯
I/flutter (28888): 
I/flutter (28888): The relevant error-causing widget was:
I/flutter (28888):   PagedListView<int, PostModel> file:///D:/Flutter/womenly/lib/screens/posts/posts_list.dart:74:12
I/flutter (28888): 
I/flutter (28888): When the exception was thrown, this was the stack:
I/flutter (28888): #0      ContainerRenderObjectMixin.debugValidateChild.<anonymous closure> (package:flutter/src/rendering/object.dart:3123:9)
I/flutter (28888): #1      ContainerRenderObjectMixin.debugValidateChild (package:flutter/src/rendering/object.dart:3150:6)
I/flutter (28888): #2      MultiChildRenderObjectElement.insertRenderObjectChild (package:flutter/src/widgets/framework.dart:6191:25)
I/flutter (28888): #3      RenderObjectElement.attachRenderObject (package:flutter/src/widgets/framework.dart:5805:35)
I/flutter (28888): #4      RenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5501:5)
I/flutter (28888): ...     Normal element mounting (37 frames)
I/flutter (28888): #41     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #42     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): #43     _ViewportElement.mount (package:flutter/src/widgets/viewport.dart:225:11)
I/flutter (28888): ...     Normal element mounting (127 frames)
I/flutter (28888): #170    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #171    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (103 frames)
I/flutter (28888): #274    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #275    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (208 frames)
I/flutter (28888): #483    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #484    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (70 frames)
I/flutter (28888): #554    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #555    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (210 frames)
I/flutter (28888): #765    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #766    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6236:32)
I/flutter (28888): ...     Normal element mounting (156 frames)
I/flutter (28888): #922    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3569:14)
I/flutter (28888): #923    Element.updateChild (package:flutter/src/widgets/framework.dart:3324:20)
I/flutter (28888): #924    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4652:16)
I/flutter (28888): #925    StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
I/flutter (28888): #926    Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
I/flutter (28888): #927    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
I/flutter (28888): #928    WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
I/flutter (28888): #929    RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
I/flutter (28888): #930    SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
I/flutter (28888): #931    SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
I/flutter (28888): #932    SchedulerBinding.scheduleWarmUpFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:864:7)
I/flutter (28888): (elided 11 frames from class _RawReceivePortImpl, class _Timer, dart:async, and dart:async-patch)
I/flutter (28888): 
I
```

**Comment by Purus** [comment]
My bad.. after replacing `PagedListView` with `PagedSliverList`, it's all fine.
